### ISSUE TITLE
Enable playing in order without shuffling?

### ISSUE THREAD

**Issue by nmehta94** [maplestory-music/maplestory-music.github.io#14]
Would it be possible to add a function to play the tracks in order based on user inputted filters to the track list? Use case - want to listen to the tracks in the order they released in, rather than needing to shuffle the tracks in order for a single track to not play on repeat. Thank you!

**Comment by nanochromatic** [comment]
Appreciate the idea! I've added this feature; you can now listen to a playlist in-order through the "Start Playlist" option.

**Comment by nmehta94** [comment]
Just saw this - this is great tysm!
