### ISSUE TITLE
Feature request: shuffle music in date range

### ISSUE THREAD

**Issue by firmart** [maplestory-music/maplestory-music.github.io#5]
It would be nice to be able to shuffle in a specific date range (or at least something like "before `2008`"). 

Also, it seems that the date sort is a bit broken:

![Screenshot from 2020-08-22 20-58-48](https://user-images.githubusercontent.com/20540328/90963713-723ef500-e4ba-11ea-86c9-168bf82c2cb6.png)
(first page, oldest first)

**Comment by nanochromatic** [comment]
It looks like you're in the neutral sort order for date. This will display the songs as they're ordered in the data (by folder). Sorting ascending/descending is functional for the date and is indicated by the arrow next to the column header.

I'll consider adding an advanced shuffle feature in the future.

**Comment by firmart** [comment]
Thanks. Indeed, I didn't notice the neutral sort order.

**Comment by nanochromatic** [comment]
This has been implemented: the shuffle song pool is now limited to the filtered records in the grid. You can filter by column(s) (eg. date, folder, etc.) or use the quick filter up top.

**Comment by firmart** [comment]
Thank you !
