### ISSUE TITLE
Request for join development!

### ISSUE THREAD

**Issue by jcs090218** [maplestory-music/maplestory-music.github.io#9]
I have sent you an email but I reckon you may not aware of it! I would just opened the issue instead. :)

---

Hi, Wesley!

Hope you are doing well! I am a big fan of your maplestory music project. I wonder if you need any help with the development? I guess you are 99% done but I would still like to ask if you can invite me to the org and I can do simple tasks.

I am just a big fan of MapleStory and would like to join any project that has something to do with the game! :D

Let me know what you think! It's okay if you don't feel like it! >_<

**Comment by nanochromatic** [comment]
Thanks for reaching out! I don't have any outstanding tasks at the moment, but I'll connect with you if there's anything that comes up!
